# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import artwork_pb2 as artwork__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artwork_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtworkServiceStub:
    """Service exposed by the Artwork microservice.
    Every RPC now carries a Lamport logical timestamp so both
    services can maintain a consistent event ordering without
    relying on synchronized wall-clock time.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtwork = channel.unary_unary(
                '/artistalley.ArtworkService/GetArtwork',
                request_serializer=artwork__pb2.ArtworkRequest.SerializeToString,
                response_deserializer=artwork__pb2.ArtworkResponse.FromString,
                _registered_method=True)
        self.ListArtworksByCategory = channel.unary_stream(
                '/artistalley.ArtworkService/ListArtworksByCategory',
                request_serializer=artwork__pb2.CategoryRequest.SerializeToString,
                response_deserializer=artwork__pb2.ArtworkResponse.FromString,
                _registered_method=True)


class ArtworkServiceServicer:
    """Service exposed by the Artwork microservice.
    Every RPC now carries a Lamport logical timestamp so both
    services can maintain a consistent event ordering without
    relying on synchronized wall-clock time.
    """

    def GetArtwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtworksByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArtwork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtwork,
                    request_deserializer=artwork__pb2.ArtworkRequest.FromString,
                    response_serializer=artwork__pb2.ArtworkResponse.SerializeToString,
            ),
            'ListArtworksByCategory': grpc.unary_stream_rpc_method_handler(
                    servicer.ListArtworksByCategory,
                    request_deserializer=artwork__pb2.CategoryRequest.FromString,
                    response_serializer=artwork__pb2.ArtworkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.ArtworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.ArtworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtworkService:
    """Service exposed by the Artwork microservice.
    Every RPC now carries a Lamport logical timestamp so both
    services can maintain a consistent event ordering without
    relying on synchronized wall-clock time.
    """

    @staticmethod
    def GetArtwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.ArtworkService/GetArtwork',
            artwork__pb2.ArtworkRequest.SerializeToString,
            artwork__pb2.ArtworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArtworksByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/artistalley.ArtworkService/ListArtworksByCategory',
            artwork__pb2.CategoryRequest.SerializeToString,
            artwork__pb2.ArtworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """--- Experiment 4: Peer-to-peer mutual exclusion (Ricart-Agrawala) ---
    Every Artist node runs this server AND calls it on its peers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/artistalley.MutexService/RequestAccess',
                request_serializer=artwork__pb2.AccessRequest.SerializeToString,
                response_deserializer=artwork__pb2.AccessReply.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """--- Experiment 4: Peer-to-peer mutual exclusion (Ricart-Agrawala) ---
    Every Artist node runs this server AND calls it on its peers.
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=artwork__pb2.AccessRequest.FromString,
                    response_serializer=artwork__pb2.AccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """--- Experiment 4: Peer-to-peer mutual exclusion (Ricart-Agrawala) ---
    Every Artist node runs this server AND calls it on its peers.
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.MutexService/RequestAccess',
            artwork__pb2.AccessRequest.SerializeToString,
            artwork__pb2.AccessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServiceStub:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/artistalley.LockService/AcquireLock',
                request_serializer=artwork__pb2.LockRequest.SerializeToString,
                response_deserializer=artwork__pb2.LockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/artistalley.LockService/ReleaseLock',
                request_serializer=artwork__pb2.LockRequest.SerializeToString,
                response_deserializer=artwork__pb2.LockReply.FromString,
                _registered_method=True)


class LockServiceServicer:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=artwork__pb2.LockRequest.FromString,
                    response_serializer=artwork__pb2.LockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=artwork__pb2.LockRequest.FromString,
                    response_serializer=artwork__pb2.LockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.LockService/AcquireLock',
            artwork__pb2.LockRequest.SerializeToString,
            artwork__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.LockService/ReleaseLock',
            artwork__pb2.LockRequest.SerializeToString,
            artwork__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProctorServiceStub:
    """--- Experiment 6: Least Connections load balancing ---
    Proctoring servers verify submissions. The LoadBalancer sits in
    front of N identical ProctorService backends and routes each
    incoming request to whichever backend currently has the fewest
    active (in-flight) connections.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifySubmission = channel.unary_unary(
                '/artistalley.ProctorService/VerifySubmission',
                request_serializer=artwork__pb2.VerifyRequest.SerializeToString,
                response_deserializer=artwork__pb2.VerifyReply.FromString,
                _registered_method=True)


class ProctorServiceServicer:
    """--- Experiment 6: Least Connections load balancing ---
    Proctoring servers verify submissions. The LoadBalancer sits in
    front of N identical ProctorService backends and routes each
    incoming request to whichever backend currently has the fewest
    active (in-flight) connections.
    """

    def VerifySubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProctorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifySubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySubmission,
                    request_deserializer=artwork__pb2.VerifyRequest.FromString,
                    response_serializer=artwork__pb2.VerifyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.ProctorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.ProctorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProctorService:
    """--- Experiment 6: Least Connections load balancing ---
    Proctoring servers verify submissions. The LoadBalancer sits in
    front of N identical ProctorService backends and routes each
    incoming request to whichever backend currently has the fewest
    active (in-flight) connections.
    """

    @staticmethod
    def VerifySubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.ProctorService/VerifySubmission',
            artwork__pb2.VerifyRequest.SerializeToString,
            artwork__pb2.VerifyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
