# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import artwork_pb2 as artwork__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artwork_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtworkServiceStub:
    """Service exposed by the Artwork microservice.
    Every RPC now carries a Lamport logical timestamp so both
    services can maintain a consistent event ordering without
    relying on synchronized wall-clock time.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtwork = channel.unary_unary(
                '/artistalley.ArtworkService/GetArtwork',
                request_serializer=artwork__pb2.ArtworkRequest.SerializeToString,
                response_deserializer=artwork__pb2.ArtworkResponse.FromString,
                _registered_method=True)
        self.ListArtworksByCategory = channel.unary_stream(
                '/artistalley.ArtworkService/ListArtworksByCategory',
                request_serializer=artwork__pb2.CategoryRequest.SerializeToString,
                response_deserializer=artwork__pb2.ArtworkResponse.FromString,
                _registered_method=True)


class ArtworkServiceServicer:
    """Service exposed by the Artwork microservice.
    Every RPC now carries a Lamport logical timestamp so both
    services can maintain a consistent event ordering without
    relying on synchronized wall-clock time.
    """

    def GetArtwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtworksByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArtwork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtwork,
                    request_deserializer=artwork__pb2.ArtworkRequest.FromString,
                    response_serializer=artwork__pb2.ArtworkResponse.SerializeToString,
            ),
            'ListArtworksByCategory': grpc.unary_stream_rpc_method_handler(
                    servicer.ListArtworksByCategory,
                    request_deserializer=artwork__pb2.CategoryRequest.FromString,
                    response_serializer=artwork__pb2.ArtworkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.ArtworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.ArtworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtworkService:
    """Service exposed by the Artwork microservice.
    Every RPC now carries a Lamport logical timestamp so both
    services can maintain a consistent event ordering without
    relying on synchronized wall-clock time.
    """

    @staticmethod
    def GetArtwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.ArtworkService/GetArtwork',
            artwork__pb2.ArtworkRequest.SerializeToString,
            artwork__pb2.ArtworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArtworksByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/artistalley.ArtworkService/ListArtworksByCategory',
            artwork__pb2.CategoryRequest.SerializeToString,
            artwork__pb2.ArtworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """--- Experiment 4: Peer-to-peer mutual exclusion (Ricart-Agrawala) ---
    Every Artist node runs this server AND calls it on its peers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/artistalley.MutexService/RequestAccess',
                request_serializer=artwork__pb2.AccessRequest.SerializeToString,
                response_deserializer=artwork__pb2.AccessReply.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """--- Experiment 4: Peer-to-peer mutual exclusion (Ricart-Agrawala) ---
    Every Artist node runs this server AND calls it on its peers.
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=artwork__pb2.AccessRequest.FromString,
                    response_serializer=artwork__pb2.AccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """--- Experiment 4: Peer-to-peer mutual exclusion (Ricart-Agrawala) ---
    Every Artist node runs this server AND calls it on its peers.
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.MutexService/RequestAccess',
            artwork__pb2.AccessRequest.SerializeToString,
            artwork__pb2.AccessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServiceStub:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/artistalley.LockService/AcquireLock',
                request_serializer=artwork__pb2.LockRequest.SerializeToString,
                response_deserializer=artwork__pb2.LockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/artistalley.LockService/ReleaseLock',
                request_serializer=artwork__pb2.LockRequest.SerializeToString,
                response_deserializer=artwork__pb2.LockReply.FromString,
                _registered_method=True)


class LockServiceServicer:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=artwork__pb2.LockRequest.FromString,
                    response_serializer=artwork__pb2.LockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=artwork__pb2.LockRequest.FromString,
                    response_serializer=artwork__pb2.LockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.LockService/AcquireLock',
            artwork__pb2.LockRequest.SerializeToString,
            artwork__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.LockService/ReleaseLock',
            artwork__pb2.LockRequest.SerializeToString,
            artwork__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MediaServiceStub:
    """--- Experiment 6: Least Connections load balancing ---
    Media Service replicas handle artwork image uploads/processing
    (resize, thumbnail generation, metadata extraction) - genuinely
    variable-latency work depending on file size/resolution. The
    LoadBalancer sits in front of N identical MediaService backends
    and routes each incoming upload to whichever backend currently
    has the fewest active (in-flight) connections.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessImage = channel.unary_unary(
                '/artistalley.MediaService/ProcessImage',
                request_serializer=artwork__pb2.ImageRequest.SerializeToString,
                response_deserializer=artwork__pb2.ImageReply.FromString,
                _registered_method=True)


class MediaServiceServicer:
    """--- Experiment 6: Least Connections load balancing ---
    Media Service replicas handle artwork image uploads/processing
    (resize, thumbnail generation, metadata extraction) - genuinely
    variable-latency work depending on file size/resolution. The
    LoadBalancer sits in front of N identical MediaService backends
    and routes each incoming upload to whichever backend currently
    has the fewest active (in-flight) connections.
    """

    def ProcessImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=artwork__pb2.ImageRequest.FromString,
                    response_serializer=artwork__pb2.ImageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService:
    """--- Experiment 6: Least Connections load balancing ---
    Media Service replicas handle artwork image uploads/processing
    (resize, thumbnail generation, metadata extraction) - genuinely
    variable-latency work depending on file size/resolution. The
    LoadBalancer sits in front of N identical MediaService backends
    and routes each incoming upload to whichever backend currently
    has the fewest active (in-flight) connections.
    """

    @staticmethod
    def ProcessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.MediaService/ProcessImage',
            artwork__pb2.ImageRequest.SerializeToString,
            artwork__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DraftServiceStub:
    """--- Experiment 7: Eventual Consistency for auto-save sync ---
    Draft replicas accept auto-save writes locally and immediately
    (availability first), then asynchronously gossip the update to
    peer replicas. Conflicts are resolved with Last-Write-Wins using
    the Lamport timestamp - reusing the same clock discipline as
    Experiment 3. All replicas eventually converge to the same state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveDraft = channel.unary_unary(
                '/artistalley.DraftService/SaveDraft',
                request_serializer=artwork__pb2.DraftUpdate.SerializeToString,
                response_deserializer=artwork__pb2.SaveAck.FromString,
                _registered_method=True)
        self.SyncUpdate = channel.unary_unary(
                '/artistalley.DraftService/SyncUpdate',
                request_serializer=artwork__pb2.DraftUpdate.SerializeToString,
                response_deserializer=artwork__pb2.SaveAck.FromString,
                _registered_method=True)
        self.GetDraft = channel.unary_unary(
                '/artistalley.DraftService/GetDraft',
                request_serializer=artwork__pb2.DraftQuery.SerializeToString,
                response_deserializer=artwork__pb2.DraftState.FromString,
                _registered_method=True)


class DraftServiceServicer:
    """--- Experiment 7: Eventual Consistency for auto-save sync ---
    Draft replicas accept auto-save writes locally and immediately
    (availability first), then asynchronously gossip the update to
    peer replicas. Conflicts are resolved with Last-Write-Wins using
    the Lamport timestamp - reusing the same clock discipline as
    Experiment 3. All replicas eventually converge to the same state.
    """

    def SaveDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DraftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveDraft,
                    request_deserializer=artwork__pb2.DraftUpdate.FromString,
                    response_serializer=artwork__pb2.SaveAck.SerializeToString,
            ),
            'SyncUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUpdate,
                    request_deserializer=artwork__pb2.DraftUpdate.FromString,
                    response_serializer=artwork__pb2.SaveAck.SerializeToString,
            ),
            'GetDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDraft,
                    request_deserializer=artwork__pb2.DraftQuery.FromString,
                    response_serializer=artwork__pb2.DraftState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artistalley.DraftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artistalley.DraftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DraftService:
    """--- Experiment 7: Eventual Consistency for auto-save sync ---
    Draft replicas accept auto-save writes locally and immediately
    (availability first), then asynchronously gossip the update to
    peer replicas. Conflicts are resolved with Last-Write-Wins using
    the Lamport timestamp - reusing the same clock discipline as
    Experiment 3. All replicas eventually converge to the same state.
    """

    @staticmethod
    def SaveDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.DraftService/SaveDraft',
            artwork__pb2.DraftUpdate.SerializeToString,
            artwork__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.DraftService/SyncUpdate',
            artwork__pb2.DraftUpdate.SerializeToString,
            artwork__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artistalley.DraftService/GetDraft',
            artwork__pb2.DraftQuery.SerializeToString,
            artwork__pb2.DraftState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
