# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artwork.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'artwork.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rartwork.proto\x12\x0b\x61rtistalley\"$\n\x0e\x41rtworkRequest\x12\x12\n\nartwork_id\x18\x01 \x01(\x05\"#\n\x0f\x43\x61tegoryRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\x93\x01\n\x0f\x41rtworkResponse\x12\x12\n\nartwork_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\r\n\x05views\x18\x06 \x01(\x05\x12\r\n\x05likes\x18\x07 \x01(\x05\x12\x0e\n\x06status\x18\x08 \x01(\t2\xb1\x01\n\x0e\x41rtworkService\x12G\n\nGetArtwork\x12\x1b.artistalley.ArtworkRequest\x1a\x1c.artistalley.ArtworkResponse\x12V\n\x16ListArtworksByCategory\x12\x1c.artistalley.CategoryRequest\x1a\x1c.artistalley.ArtworkResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artwork_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTWORKREQUEST']._serialized_start=30
  _globals['_ARTWORKREQUEST']._serialized_end=66
  _globals['_CATEGORYREQUEST']._serialized_start=68
  _globals['_CATEGORYREQUEST']._serialized_end=103
  _globals['_ARTWORKRESPONSE']._serialized_start=106
  _globals['_ARTWORKRESPONSE']._serialized_end=253
  _globals['_ARTWORKSERVICE']._serialized_start=256
  _globals['_ARTWORKSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
